"""Add skipped column to guesses

Revision ID: 4f4b898bf26b
Revises: add_irregular_to_guesses
Create Date: 2025-09-18 09:37:26.661982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4b898bf26b'
down_revision: Union[str, Sequence[str], None] = 'add_irregular_to_guesses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guesses', sa.Column('skipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guesses', 'skipped')
    # ### end Alembic commands ###
