"""Add verb, round models and rename question to guess

Revision ID: 6fcd840b7647
Revises: add_questions_table
Create Date: 2025-08-31 10:18:36.747369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fcd840b7647'
down_revision: Union[str, Sequence[str], None] = 'add_questions_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('num_correct_answers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infinitive', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('infinitive')
    )
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('verb_id', sa.Integer(), nullable=True),
    sa.Column('pronoun', sa.String(length=20), nullable=False),
    sa.Column('tense', sa.String(length=50), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('user_answer', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pronoun', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tense', postgresql.ENUM('present', 'imperfect', 'preterite', 'future', 'present_perfect', 'past_anterior', 'future_perfect', 'conditional_simple', name='tenseenum'), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verb', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mood', postgresql.ENUM('conditional', 'imperative', 'indicative', 'subjunctive', name='moodenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.drop_table('guesses')
    op.drop_table('verbs')
    op.drop_table('rounds')
    # ### end Alembic commands ###
