"""Add tubelex_count and tubelex_rank to Verb model

Revision ID: c8a1b429b45c
Revises: 6fcd840b7647
Create Date: 2025-09-03 17:22:40.842492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a1b429b45c'
down_revision: Union[str, Sequence[str], None] = '6fcd840b7647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verbs', sa.Column('tubelex_count', sa.Integer(), nullable=True))
    op.add_column('verbs', sa.Column('tubelex_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verbs', 'tubelex_rank')
    op.drop_column('verbs', 'tubelex_count')
    # ### end Alembic commands ###
